In [1]:
import torch

In [33]:
x = torch.ones(1)
y = torch.rand(1)

w = torch.zeros(1,requires_grad = True)

In [34]:
print(x)
print(y)
print(w)

tensor([1.])
tensor([0.0124])
tensor([0.], requires_grad=True)


In [10]:
y_hat = x*w
s = y_hat - y
loss = s**2
print(loss)

tensor([0.8812], grad_fn=<PowBackward0>)


In [11]:
loss.backward()

In [14]:
print(w.grad)

tensor([1.8774])


## Gradient Descent From Scratch

In [15]:
import numpy as np

In [61]:
x = np.array([1,2,3,4,5])
y = np.array([2,4,6,8,10]) ## y = 3*x
# weight initialization
w = np.array([0.],dtype=np.float32)

In [62]:
def forward_pass(x):
    return w*x

def loss(y,y_predicted):
    return ((y-y_predicted)**2).mean()

def gradient_descent(x,y,y_predicted):
    return (1/len(x))*(np.dot(2*x,(y_predicted-y)))

In [63]:
y_pred = forward_pass(x)
print("Predicted value with initial weights: {:.3f}",y_pred)

epochs = 10
learning_rate = 0.01
for epoch in range(epochs):
    y_pred = forward_pass(x)
    loss_value = loss(y,y_pred)
    dw = gradient_descent(x,y,y_pred)
    w = w - learning_rate*dw
    print(f"Predicted value at epoch number : {epoch}: {w[0]:.3f} and loss = {loss_value:.3f}")

Predicted value with initial weights: {:.3f} [0. 0. 0. 0. 0.]
Predicted value at epoch number : 0: 0.440 and loss = 44.000
Predicted value at epoch number : 1: 0.783 and loss = 26.770
Predicted value at epoch number : 2: 1.051 and loss = 16.287
Predicted value at epoch number : 3: 1.260 and loss = 9.909
Predicted value at epoch number : 4: 1.423 and loss = 6.029
Predicted value at epoch number : 5: 1.550 and loss = 3.668
Predicted value at epoch number : 6: 1.649 and loss = 2.231
Predicted value at epoch number : 7: 1.726 and loss = 1.358
Predicted value at epoch number : 8: 1.786 and loss = 0.826
Predicted value at epoch number : 9: 1.833 and loss = 0.503


# Gradient Descent with Pytorch from scratch

In [64]:
import torch

In [79]:
x = torch.tensor([1,2,3,4,5],dtype=torch.float32)
y = torch.tensor([3,6,9,12,15],dtype=torch.float32)
w = torch.tensor([0.],requires_grad = True)

In [80]:
def forward(x):
    return w*x

def loss(y,y_pred):
    return ((y-y_pred)**2).mean()

In [81]:
epochs = 100
learning_rate = 0.002

for epoch in range(epochs):
    y_pred = forward_pass(x)
    
    l = loss(y,y_pred)
    
    l.backward() #dl/dw
    
    #update weights
    ## ---------IMPORTANT STEP ----------------------
    with torch.no_grad():
        w -= learning_rate*w.grad
    
    w.grad.zero_()
    
    if (epoch +1)%10 == 0:
        print(f"Prediction after epoch -> {epoch}: weights : {w[0]:.3f}, loss: {l:.3f}")

Prediction after epoch -> 9: weights : 1.087, loss: 44.043
Prediction after epoch -> 19: weights : 1.780, loss: 17.908
Prediction after epoch -> 29: weights : 2.222, loss: 7.281
Prediction after epoch -> 39: weights : 2.504, loss: 2.960
Prediction after epoch -> 49: weights : 2.684, loss: 1.204
Prediction after epoch -> 59: weights : 2.798, loss: 0.489
Prediction after epoch -> 69: weights : 2.871, loss: 0.199
Prediction after epoch -> 79: weights : 2.918, loss: 0.081
Prediction after epoch -> 89: weights : 2.948, loss: 0.033
Prediction after epoch -> 99: weights : 2.967, loss: 0.013


# Implementation of Feedforward Neural network using torch.nn

In [82]:
import torch
import torch.nn as nn

In [119]:
## Inputs now must be in the shape of rows and features, see below for more understanding
x = torch.tensor([[1],[3],[5],[7]],dtype=torch.float32)
y = torch.tensor([[2],[6],[10],[14]],dtype=torch.float32)

In [125]:
nsamples,nfeatures = x.shape
print(x.shape)

torch.Size([4, 1])


In [126]:
input_size = nfeatures
output_size = nfeatures

In [127]:
model = nn.Linear(input_size,output_size)
learning_rate = 0.01
epochs = 200

In [128]:
loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)

In [129]:
for epoch in range(epochs):
    y_pred = model(x)
    
    l = loss(y,y_pred)
    
    l.backward()
    
    optimizer.step()
    
    optimizer.zero_grad()
    
    if epoch %20 == 0:
        w,b = model.parameters()
        print(f"prediction after epoch : {epoch} : weight : {w[0][0]:.3f},  loss: {l:.3f}")
    

prediction after epoch : 0 : weight : 0.222,  loss: 175.121
prediction after epoch : 20 : weight : 1.811,  loss: 0.231
prediction after epoch : 40 : weight : 1.828,  loss: 0.192
prediction after epoch : 60 : weight : 1.843,  loss: 0.160
prediction after epoch : 80 : weight : 1.857,  loss: 0.133
prediction after epoch : 100 : weight : 1.869,  loss: 0.111
prediction after epoch : 120 : weight : 1.881,  loss: 0.092
prediction after epoch : 140 : weight : 1.891,  loss: 0.077
prediction after epoch : 160 : weight : 1.901,  loss: 0.064
prediction after epoch : 180 : weight : 1.910,  loss: 0.053
